---
all:
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.10.116
          # ansible_user: vagrant
          # ansible_password: vagrant
        web02:
          ansible_host: 192.168.10.117
          # ansible_user: vagrant
          # ansible_password: vagrant
    monitoring:
      hosts:
        mon1:
          ansible_host: 192.168.10.118
          # ansible_user: vagrant
          # ansible_password: vagrant
