---
all:
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.10.119
          # ansible_user: vagrant
          # ansible_password: vagrant
        web02:
          ansible_host: 192.168.10.120
          # ansible_user: vagrant
          # ansible_password: vagrant
    monitoring:
      hosts:
        mon1:
          ansible_host: 192.168.10.121
          # ansible_user: vagrant
          # ansible_password: vagrant
    db:
      hosts:
        db01:
          ansible_host: 192.168.10.122
          # ansible_user: vagrant
          # ansible_password: vagrant
        db02:
          ansible_host: 192.168.10.123
          # ansible_user: vagrant
          # ansible_password: vagrant

