# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.define "web01" do |server|
  end
  config.vm.define "web02" do |server|
  end
  config.vm.define "mon01" do |server|
  end
  config.vm.define "db01" do |server|
  end
  config.vm.define "db02" do |server|
  end
end
